// Country calling codes (ITU-T E.164 country codes), one entry per ISO
// 3166-1 alpha-2 territory. Several countries share a code (e.g. +1 for
// the NANP, +7 for Russia/Kazakhstan) — that's expected, not a typo.
export const COUNTRY_CODES = [
  ['US', 'United States', '1'], ['CA', 'Canada', '1'],
  ['GB', 'United Kingdom', '44'], ['IE', 'Ireland', '353'],
  ['IN', 'India', '91'], ['AU', 'Australia', '61'], ['NZ', 'New Zealand', '64'],
  ['DE', 'Germany', '49'], ['FR', 'France', '33'], ['ES', 'Spain', '34'],
  ['PT', 'Portugal', '351'], ['IT', 'Italy', '39'], ['NL', 'Netherlands', '31'],
  ['BE', 'Belgium', '32'], ['LU', 'Luxembourg', '352'], ['CH', 'Switzerland', '41'],
  ['AT', 'Austria', '43'], ['SE', 'Sweden', '46'], ['NO', 'Norway', '47'],
  ['DK', 'Denmark', '45'], ['FI', 'Finland', '358'], ['IS', 'Iceland', '354'],
  ['PL', 'Poland', '48'], ['CZ', 'Czechia', '420'], ['SK', 'Slovakia', '421'],
  ['HU', 'Hungary', '36'], ['RO', 'Romania', '40'], ['BG', 'Bulgaria', '359'],
  ['GR', 'Greece', '30'], ['HR', 'Croatia', '385'], ['SI', 'Slovenia', '386'],
  ['RS', 'Serbia', '381'], ['BA', 'Bosnia and Herzegovina', '387'],
  ['MK', 'North Macedonia', '389'], ['AL', 'Albania', '355'],
  ['ME', 'Montenegro', '382'], ['XK', 'Kosovo', '383'],
  ['EE', 'Estonia', '372'], ['LV', 'Latvia', '371'], ['LT', 'Lithuania', '370'],
  ['UA', 'Ukraine', '380'], ['BY', 'Belarus', '375'], ['MD', 'Moldova', '373'],
  ['RU', 'Russia', '7'], ['KZ', 'Kazakhstan', '7'], ['GE', 'Georgia', '995'],
  ['AM', 'Armenia', '374'], ['AZ', 'Azerbaijan', '994'],
  ['TR', 'Turkey', '90'], ['CY', 'Cyprus', '357'], ['MT', 'Malta', '356'],
  ['IL', 'Israel', '972'], ['PS', 'Palestine', '970'], ['JO', 'Jordan', '962'],
  ['LB', 'Lebanon', '961'], ['SY', 'Syria', '963'], ['IQ', 'Iraq', '964'],
  ['IR', 'Iran', '98'], ['SA', 'Saudi Arabia', '966'], ['AE', 'United Arab Emirates', '971'],
  ['QA', 'Qatar', '974'], ['BH', 'Bahrain', '973'], ['KW', 'Kuwait', '965'],
  ['OM', 'Oman', '968'], ['YE', 'Yemen', '967'],
  ['EG', 'Egypt', '20'], ['LY', 'Libya', '218'], ['TN', 'Tunisia', '216'],
  ['DZ', 'Algeria', '213'], ['MA', 'Morocco', '212'], ['SD', 'Sudan', '249'],
  ['ET', 'Ethiopia', '251'], ['KE', 'Kenya', '254'], ['TZ', 'Tanzania', '255'],
  ['UG', 'Uganda', '256'], ['RW', 'Rwanda', '250'], ['SO', 'Somalia', '252'],
  ['DJ', 'Djibouti', '253'], ['ER', 'Eritrea', '291'], ['SS', 'South Sudan', '211'],
  ['NG', 'Nigeria', '234'], ['GH', 'Ghana', '233'], ['CI', "Cote d'Ivoire", '225'],
  ['SN', 'Senegal', '221'], ['ML', 'Mali', '223'], ['BF', 'Burkina Faso', '226'],
  ['NE', 'Niger', '227'], ['TD', 'Chad', '235'], ['CM', 'Cameroon', '237'],
  ['GA', 'Gabon', '241'], ['CG', 'Congo', '242'], ['CD', 'DR Congo', '243'],
  ['AO', 'Angola', '244'], ['ZM', 'Zambia', '260'], ['ZW', 'Zimbabwe', '263'],
  ['MZ', 'Mozambique', '258'], ['MW', 'Malawi', '265'], ['NA', 'Namibia', '264'],
  ['BW', 'Botswana', '267'], ['ZA', 'South Africa', '27'], ['SZ', 'Eswatini', '268'],
  ['LS', 'Lesotho', '266'], ['MG', 'Madagascar', '261'], ['MU', 'Mauritius', '230'],
  ['SC', 'Seychelles', '248'], ['GM', 'Gambia', '220'], ['GN', 'Guinea', '224'],
  ['SL', 'Sierra Leone', '232'], ['LR', 'Liberia', '231'], ['TG', 'Togo', '228'],
  ['BJ', 'Benin', '229'], ['MR', 'Mauritania', '222'], ['CV', 'Cabo Verde', '238'],
  ['GW', 'Guinea-Bissau', '245'], ['GQ', 'Equatorial Guinea', '240'],
  ['CF', 'Central African Republic', '236'], ['BI', 'Burundi', '257'],
  ['CN', 'China', '86'], ['HK', 'Hong Kong', '852'], ['MO', 'Macao', '853'],
  ['TW', 'Taiwan', '886'], ['JP', 'Japan', '81'], ['KR', 'South Korea', '82'],
  ['KP', 'North Korea', '850'], ['MN', 'Mongolia', '976'],
  ['VN', 'Vietnam', '84'], ['TH', 'Thailand', '66'], ['MM', 'Myanmar', '95'],
  ['KH', 'Cambodia', '855'], ['LA', 'Laos', '856'], ['MY', 'Malaysia', '60'],
  ['SG', 'Singapore', '65'], ['ID', 'Indonesia', '62'], ['PH', 'Philippines', '63'],
  ['BN', 'Brunei', '673'], ['TL', 'Timor-Leste', '670'],
  ['PK', 'Pakistan', '92'], ['BD', 'Bangladesh', '880'], ['LK', 'Sri Lanka', '94'],
  ['NP', 'Nepal', '977'], ['BT', 'Bhutan', '975'], ['MV', 'Maldives', '960'],
  ['AF', 'Afghanistan', '93'], ['UZ', 'Uzbekistan', '998'], ['TM', 'Turkmenistan', '993'],
  ['TJ', 'Tajikistan', '992'], ['KG', 'Kyrgyzstan', '996'],
  ['MX', 'Mexico', '52'], ['GT', 'Guatemala', '502'], ['BZ', 'Belize', '501'],
  ['HN', 'Honduras', '504'], ['SV', 'El Salvador', '503'], ['NI', 'Nicaragua', '505'],
  ['CR', 'Costa Rica', '506'], ['PA', 'Panama', '507'], ['CU', 'Cuba', '53'],
  ['JM', 'Jamaica', '1876'], ['HT', 'Haiti', '509'], ['DO', 'Dominican Republic', '1809'],
  ['BS', 'Bahamas', '1242'], ['TT', 'Trinidad and Tobago', '1868'],
  ['BB', 'Barbados', '1246'], ['PR', 'Puerto Rico', '1787'],
  ['CO', 'Colombia', '57'], ['VE', 'Venezuela', '58'], ['GY', 'Guyana', '592'],
  ['SR', 'Suriname', '597'], ['EC', 'Ecuador', '593'], ['PE', 'Peru', '51'],
  ['BR', 'Brazil', '55'], ['BO', 'Bolivia', '591'], ['PY', 'Paraguay', '595'],
  ['UY', 'Uruguay', '598'], ['AR', 'Argentina', '54'], ['CL', 'Chile', '56'],
  ['FJ', 'Fiji', '679'], ['PG', 'Papua New Guinea', '675'], ['WS', 'Samoa', '685'],
  ['TO', 'Tonga', '676'], ['VU', 'Vanuatu', '678'], ['SB', 'Solomon Islands', '677'],
  ['KI', 'Kiribati', '686'], ['PW', 'Palau', '680'], ['FM', 'Micronesia', '691'],
  ['MH', 'Marshall Islands', '692'], ['NR', 'Nauru', '674'], ['TV', 'Tuvalu', '688'],
];
